name: Build & Publish Orthobullets Cases RSS

# Allow the workflow to push to gh-pages
permissions:
  contents: write

on:
  workflow_dispatch:     # run manually
  # schedule:            # uncomment if you want daily at 05:30 Berlin
  #   - cron: "30 3 * * *"  # 05:30 CEST (UTC+2, summer)
  #   - cron: "30 4 * * *"  # 05:30 CET (UTC+1, winter)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4 lxml

      - name: Generate RSS
        env:
          OTB_COOKIE: ${{ secrets.OTB_COOKIE }}   # optional if login needed
          OTB_URL: https://www.orthobullets.com/Site/ElasticSearch/StandardSearchTiles?contentType=5&s=1,2,3,225,6,7,10
          OTB_OUTPUT: dist/orthobullets_cases.xml
          OTB_STATE: dist/orthobullets_cases_seen.json
          OTB_XPATH: '//div[contains(@class,"dashboard-item--case")]//a[@href]'
        run: |
          mkdir -p dist
          python3 orthobullets_cases_rss.py
          ls -l dist

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          enable_jekyll: false
