name: Build & Publish Orthobullets Cases RSS (Login, 24h filter)

permissions:
  contents: write

on:
  # run daily at 06:00 Berlin (handles DST by running both UTC times)
  schedule:
    - cron: "0 5 * * *"  # 05:00 UTC ≈ 06:00 CEST (summer)
    - cron: "0 4 * * *"  # 04:00 UTC ≈ 06:00 CET  (winter)
  workflow_dispatch: {}   # also allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Playwright + parsers)
        run: |
          pip install playwright lxml requests
          python -m playwright install --with-deps chromium

      - name: Generate RSS/JSON (login, XPath, last 24h)
        env:
          OTB_EMAIL: ${{ secrets.OTB_EMAIL }}
          OTB_PASSWORD: ${{ secrets.OTB_PASSWORD }}
          OTB_URL: https://www.orthobullets.com/Site/ElasticSearch/StandardSearchTiles?contentType=5&s=1,2,3,225,6,7,10
          OTB_XPATH: //div[contains(@class,"dashboard-item--case")]//a[@href]
          OTB_OUTPUT: dist/orthobullets_cases.xml
          OTB_JSON: dist/orthobullets_cases.json
          OTB_STATE: dist/orthobullets_cases_seen.json
          OTB_UA: Mozilla/5.0 (Orthobullets RSS Bot)
          OTB_MAX_ITEMS: "60"
          # set to "1" if you want pages without a detectable date to be included
          OTB_INCLUDE_UNDATED: "0"
        run: |
          mkdir -p dist
          python3 orthobullets_cases_rss.py
          echo "Produced files:"
          ls -l dist

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          enable_jekyll: false
